listen_addresses: '$LISTEN_ADDRESSES'

connection_string: '$DATABASE_URL'

pool_size: 20

keep_alive: 75

woker_processes: 8

watch: false

danger_accept_invalid_certs: true


table_sources:


  zambia.poverty:

    id: zambia.poverty

    schema: zambia

    table: poverty

    bounds: [21.99937097299215, -18.07947250185431, 33.70570457620539, -8.224360000713332]

    srid: 3857

    geometry_column: geom

    id_column: ~

    extent: 4096

    buffer: 64

    geometry_type: MULTIPOLYGON

    clip_geometry: true


    properties:

      id: int4

      ctr: float8

      fid: int8

      cst_n: varchar

      ctr_n: varchar

      cst_n_1: varchar

      district: varchar

      gred_cst: float8

      num_poor: float8

      province: varchar

      std_error: float8

      constitu_1: float8

      constituen: varchar

      districtco: float8

      povertyhea: float8

      provinceco: float8
