version: "3"

services:
  martin:
    image: ghcr.io/undp-data/martin-docker:latest
    build: .
    restart: unless-stopped
    container_name: martin_geohub
    ports:
      - "80:3000"
    env_file:
      - .env
    # volumes:
    #   - ./:/etc/martin/:rw



