version: "3"
services:
  martin:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: martin-reactive:latest
    restart: unless-stopped
    container_name: martin
    ports:
      - "3000:3000"
    env_file:
      - .env

