version: "3"

services:
  martin:
    image: ghcr.io/undp-data/martin-docker:latest
    #pull_policy: always
    restart: unless-stopped
    container_name: martin
    ports:
      - "3000:3000"
    env_file:
      - .env



